_target_: "proteinworkshop.models.graph_encoders.pronet.ProNet"
level: 'aminoacid'
num_blocks: 4
hidden_channels: 128
out_channels: 1
mid_emb: 64
num_radial: 6
num_spherical: 2
cutoff: 10.0
max_num_neighbors: 32
int_emb_layers: 3
out_layers: 2
num_pos_emb: 16
dropout: 0.3
data_augment_eachlayer: True
euler_noise: False
pretraining: False
node_embedding: False
